/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppYieldRouteImport } from './routes/app.yield'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppIrrigationRouteImport } from './routes/app.irrigation'
import { Route as AppFertilizerRouteImport } from './routes/app.fertilizer'
import { Route as AppDiseaseRouteImport } from './routes/app.disease'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCropRouteImport } from './routes/app.crop'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppYieldRoute = AppYieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppIrrigationRoute = AppIrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => AppRoute,
} as any)
const AppFertilizerRoute = AppFertilizerRouteImport.update({
  id: '/fertilizer',
  path: '/fertilizer',
  getParentRoute: () => AppRoute,
} as any)
const AppDiseaseRoute = AppDiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCropRoute = AppCropRouteImport.update({
  id: '/crop',
  path: '/crop',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/crop': typeof AppCropRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/disease': typeof AppDiseaseRoute
  '/app/fertilizer': typeof AppFertilizerRoute
  '/app/irrigation': typeof AppIrrigationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/yield': typeof AppYieldRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/crop': typeof AppCropRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/disease': typeof AppDiseaseRoute
  '/app/fertilizer': typeof AppFertilizerRoute
  '/app/irrigation': typeof AppIrrigationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/yield': typeof AppYieldRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/crop': typeof AppCropRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/disease': typeof AppDiseaseRoute
  '/app/fertilizer': typeof AppFertilizerRoute
  '/app/irrigation': typeof AppIrrigationRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/yield': typeof AppYieldRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/crop'
    | '/app/dashboard'
    | '/app/disease'
    | '/app/fertilizer'
    | '/app/irrigation'
    | '/app/profile'
    | '/app/settings'
    | '/app/yield'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/crop'
    | '/app/dashboard'
    | '/app/disease'
    | '/app/fertilizer'
    | '/app/irrigation'
    | '/app/profile'
    | '/app/settings'
    | '/app/yield'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/crop'
    | '/app/dashboard'
    | '/app/disease'
    | '/app/fertilizer'
    | '/app/irrigation'
    | '/app/profile'
    | '/app/settings'
    | '/app/yield'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/yield': {
      id: '/app/yield'
      path: '/yield'
      fullPath: '/app/yield'
      preLoaderRoute: typeof AppYieldRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/irrigation': {
      id: '/app/irrigation'
      path: '/irrigation'
      fullPath: '/app/irrigation'
      preLoaderRoute: typeof AppIrrigationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fertilizer': {
      id: '/app/fertilizer'
      path: '/fertilizer'
      fullPath: '/app/fertilizer'
      preLoaderRoute: typeof AppFertilizerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/disease': {
      id: '/app/disease'
      path: '/disease'
      fullPath: '/app/disease'
      preLoaderRoute: typeof AppDiseaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crop': {
      id: '/app/crop'
      path: '/crop'
      fullPath: '/app/crop'
      preLoaderRoute: typeof AppCropRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCropRoute: typeof AppCropRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiseaseRoute: typeof AppDiseaseRoute
  AppFertilizerRoute: typeof AppFertilizerRoute
  AppIrrigationRoute: typeof AppIrrigationRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppYieldRoute: typeof AppYieldRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCropRoute: AppCropRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiseaseRoute: AppDiseaseRoute,
  AppFertilizerRoute: AppFertilizerRoute,
  AppIrrigationRoute: AppIrrigationRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppYieldRoute: AppYieldRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
